//export const serverAddress = 'http://localhost:4000/'
export const serverAddress = 'https://flipraitnfssc.azurewebsites.net/'
export const registerAddress = serverAddress + 'register'
export const loginAddress = serverAddress + 'login'
export const forgotpassAddress = serverAddress + 'forgotpassword'
